### PR TITLE
Add newer tokens support and add support for dynamic content

### PR DESCRIPTION
**Pull request by kuzmany**
Mautic 2.11 broadcast send email wrong convert toknes and unsubscribe doesn't work.
This PR fixed it and brought also support for DynamicContent for Mautic landing pages and hope also works on pages with tracking code (not test yet).

For people who want to use this update download here https://github.com/kuzmany/mautic-vocative/tree/dynamic-content-support

### CODE REVIEW

**Comment by jaroslavtyc** [comment]
Fixed unsubscribe caused by wrong tokens replacement and added support of dynamic content (for landing pages).

**Comment by kuzmany** [comment]
What do you mean? PR use Code Standards as Mautic required and this standards are applied with every commit  https://github.com/mautic/mautic/blob/staging/.github/CONTRIBUTING.md#code-contribution-requirements

**Comment by jaroslavtyc** [comment]
In that case I will refactor whole project to Mautic standard (as it is currently formatted just "as usual" for my projects.-)

**Comment by kuzmany** [comment]
Yeah. Plugin need little more touch. For example factory is depraced, should be move to helper (like DynamicContentHelper...) https://github.com/jaroslavtyc/mautic-vocative/pull/1/files#diff-eed4ff6324c77c040358731dea5123e0R51
But maybe next time, now no free time 👍 
Thanks for great project.

**Pull request closed without merging**
